database:
  # Disponíveis: SQLite, MySQL #
  type: 'SQLite'
  sqlite:
    file: 'storage/database.sql'
  mysql:
    host: 'localhost'
    port: 3306
    username: 'root'
    password: ''
    database: 'db_neopayments'

# Gateways de pagamento #
gateways:
  mercado-pago:
    authentication: "token"

discord:
  token: "TOKEN"
  channels:
    sell: "CHANNEL_ID"
  # Embeds das mensagens que serão enviadas no Discord #
  embeds:
    sell:
      color: BLACK
      title: "Uma nova venda foi encontrada!"
      description: "Uma nova venda do produto {product} foi encontrada!"
      fields:
        player: "Comprador"
        price: "Custo"
        rate: "Taxa"
      footer: "Adquirido por {player} em {date}"

# Categorias de produtos que podem ser vendidos #
categories:
  example:
    name: "Categoria Exemplo"
    description:
      - ""
    icon:
      material: DIAMOND
      id: 0